API-REST/controladores/tareaDia.js, API-REST/modelos/TareasDia.js
Creado los comentarios al código relacionado con las tareas
=> Comentarios tarea

API-REST/controladores/tareaDia.js
Se asigna la fehca actual y null cuando se asigna / desasigna la tarea
=> controlador de las fechas de las tareas

API-REST/basedatos/conexionTests.js, API-REST/crearServidor.js, API-REST/index.js, API-REST/package-lock.json, API-REST/package.json, API-REST/tests/usuarios.test.js
Se ha reconfigurado para lanzar el crear el servidor desde una función y luego usar esa función dentro del index y lanzarlo desde allí. (Esto es necesario para los tests ). Luego he creado otro fichero para conectarnos a la base de datos de prueba. Se ha instalado jest y supertest en modo dev. Se ha añadido un test para un endpoint de la api en la carpeta tests
=> Set up tests

API-REST/package.json, API-REST/tests/tareas.test.js, API-REST/tests/usuarios.test.js
Crear la estructura para los tests de tareas y ademas crear lso tests para asignar y desasignar tareas
=> Tareas tests

front-c4a/src/componentes/Layout/TareaAsignada.js, front-c4a/src/componentes/Layout/TareaNoRealizada.js, front-c4a/src/componentes/Layout/TareaRealizada.js, front-c4a/src/componentes/Layout/TareaSinAsignar.js, front-c4a/src/componentes/Layout/Tareas.js, front-c4a/src/styles.css
=> Eliminartarea

front-c4a/src/componentes/Layout/BuscarFiltros.js, front-c4a/src/componentes/Layout/Header.js, front-c4a/src/styles.css
=> Mejora interfaz

API-REST/controladores/tareaDia.js
Ahora se devuelven el usuario y la tarea modificados en el mensaje
=> Perf(API): modificacion asignar desasignar

API-REST/rutas/tareasDia.js, API-REST/rutas/usuario.js, API-REST/tests/tareas.test.js, API-REST/tests/usuarios.test.js, front-c4a/src/componentes/Layout/Alumnos.js, front-c4a/src/componentes/Layout/Clases.js, front-c4a/src/componentes/Layout/ListaTareas.js, front-c4a/src/componentes/Layout/TareaAsignada.js, front-c4a/src/componentes/Layout/TareaNoRealizada.js, front-c4a/src/componentes/Layout/TareaRealizada.js, front-c4a/src/componentes/Layout/Tareas.js, front-c4a/src/componentes/Layout/Usuarios.js, front-c4a/src/componentes/pages/Agenda.js, front-c4a/src/componentes/pages/SesionAlumnos.js, front-c4a/src/componentes/pages/SesionAlumnosClases.js, front-c4a/src/componentes/pages/TareaEspecifica.js
-Estandarización de las rutas de la API : cambiados todas las llamadas en todos los ficheros
-Fix bug: Se filtraba erróneamente (sinasignar en vez de sinAsignar y con completada y cancelada totalmente inventada xd)
=> Perf rutas api

front-c4a/package-lock.json, front-c4a/package.json, front-c4a/src/componentes/admins/Layout/FormularioNuevoUsuario.js, front-c4a/src/componentes/compartido/Layout/Profesores.js
- Se ha cambiado el label y el input de la contraseña de los profesores, ahora es diferente del nombre de usuario
- Se ha implementado el eliminar el campo "email" cuando en crear usuario se selecciona un alumno: se ha instalado Jquery para que su implementación sea lo más sencilla posible
=> Perf(bugs): formulario crear alumno y login profes

TODO, front-c4a/package.json, front-c4a/src/componentes/alumnos/Layout/Alumnos.js, front-c4a/src/componentes/alumnos/pages/SesionAlumnos.js, front-c4a/src/componentes/compartido/pages/SesionAlumnosClases.js, front-c4a/src/componentes/flechasPaginacionGenerico.js
Ahora desaparecen las flechas de paginación en función de si hay más alumnos de los permitidos por página o no. También he mejorado la implementación del mensaje de que no hay alumnos y he puesto otro para las aulas por si acaso.
=> Arreglo paginacion en clases y alumnos

front-c4a/src/componentes/admins/Layout/FormularioNuevoMenu.js, front-c4a/src/componentes/admins/Layout/ListaMenus.js, front-c4a/src/componentes/admins/Layout/Menu.js, front-c4a/src/componentes/admins/Layout/PantallaInfoMenus.js, front-c4a/src/componentes/admins/pages/CreacionMenu.js, front-c4a/src/componentes/admins/pages/InfoMenus.js, front-c4a/src/componentes/admins/styles.css, front-c4a/src/componentes/compartido/Layout/PantallasGestion.js, front-c4a/src/componentes/muibreadcrumbs.js, front-c4a/src/routing/RouterAdmins.js
formulario de añadir menús incompleto aún
=> lista, info y añadir menús

front-c4a/src/componentes/alumnos/pages/Agenda.js, front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/routing/RouterAlumnos.js
-Página para que el alumno recoja los materiales
-Modificado el boton de agenda para diferencia entre tarea general comanda y materiales
=> Material alumno

API-REST/controladores/material.js, front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/componentes/alumnos/styles.css, front-c4a/src/componentes/compartido/Layout/Profesores.js
Página para que el alumno mande que ha recogido el material
=> Coger material

front-c4a/src/componentes/admins/pages/GestionMenus.js, front-c4a/src/componentes/admins/pages/GestionUsuarios.js, front-c4a/src/componentes/admins/pages/InfoMenus.js, front-c4a/src/componentes/alumnos/pages/Agenda.js, front-c4a/src/componentes/alumnos/pages/Comandas.js, front-c4a/src/componentes/alumnos/pages/ComandasClases.js, front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/componentes/alumnos/pages/PaginaPrincipal.js, front-c4a/src/componentes/alumnos/pages/TareaEspecifica.js, front-c4a/src/componentes/alumnos/pages/Tareas.js, front-c4a/src/componentes/compartido/pages/GestionTareas.js, front-c4a/src/componentes/compartido/pages/PedirMateriales.js, front-c4a/src/componentes/compartido/pages/SesionAlumnosClases.js
Arreglado el fallo que habéis provocado por no leeros la documentación. También he eliminado una función inútil de roles debido a la nueva implementación.
=> Arreglo de las cookies y de roles

API-REST/controladores/tareaDia.js, API-REST/modelos/TareasDia.js, API-REST/rutas/tareasDia.js
Solo se ha añadido la posibilidad de retroalimentación en formato texto, se puede mejorar añadiendo la posibilidad de añadir pictogramas
=> modelo y controlador para retroalimentación

front-c4a/src/componentes/alumnos/pages/PaginaPrincipal.js, front-c4a/src/componentes/compartido/Layout/Header.js
El cambio era sencillo, el att botonAtras toma undefined por defecto y dicho caso no se contemplaba
=> fix: botón atras

front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/componentes/alumnos/styles.css, front-c4a/src/componentes/flechasPaginacionGenerico.js
También he eliminado el XD que había puesto @javierSerLuc xdd.
=> Arreglado problema de falta de imágenes

front-c4a/src/componentes/admins/Layout/FormularioModificarUsuario.js
En el select, en vez de poner default=0 poner el valor que tiene el usuario en el sistema para que en el desplegable salga el valor que tiene en ese momento
=> Mejora Formulario cambio tamaños

front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/componentes/compartido/Layout/Materiales/MaterialPedido.js, front-c4a/src/componentes/compartido/Layout/Materiales/Materiales.js, front-c4a/src/componentes/compartido/styles.css
-Boton x del alumno cuando esta recogiendo los materiales lo marca como que no se ha encontrado
-Para cada material faltante durante la info del pedido sale un icono con texto para avisar de que ese material no se encuentra disponible
=> Avisos Falta material

front-c4a/src/componentes/alumnos/pages/EntregaMaterial.js, front-c4a/src/componentes/compartido/Layout/Materiales/MaterialPedido.js, front-c4a/src/componentes/compartido/Layout/Materiales/PedirMaterial.js
-Los botones de marcar como recogido o faltante estaban invertidos
-Fix: la petición a la api no se realizaba
=> Fix:No guardaba los mats faltantes
